#!/usr/bin/env python3
"""Sundara jāla: for a beautiful web."""

import argparse
import sundara, jala

def main():
    parser = argparse.ArgumentParser(
            epilog="report bugs to: \
                https://github.com/george2/sundara/issues",
    )
    args = parser.parse_args()

if __name__ == "__main__":
    main()
